# This file was generated by GoReleaser. DO NOT EDIT.
cask "gojo" do
  version "1.6.0"

  on_macos do
    on_intel do
      sha256 "329d1bac012483a466eda8cffdb6e834aa6fdd4bfc8d08dff3d3e3939e70c484"
      url "https://github.com/0xhckr/gojo/releases/download/v#{version}/gojo_#{version}_macOS_amd64.tar.gz",
        verified: "github.com/0xhckr/gojo/"
    end
    on_arm do
      sha256 "f93fb13caf375bc30ee6c5a1803736d3bee4e1728e2630dcf35f23fa94de7ffd"
      url "https://github.com/0xhckr/gojo/releases/download/v#{version}/gojo_#{version}_macOS_arm64.tar.gz",
        verified: "github.com/0xhckr/gojo/"
    end
  end

  on_linux do
    on_intel do
      sha256 "710342fa7a1c42d1419fa44a6867b2ae3f8f861b725f094c2613699e9e628754"
      url "https://github.com/0xhckr/gojo/releases/download/v#{version}/gojo_#{version}_linux_amd64.tar.gz",
        verified: "github.com/0xhckr/gojo/"
    end
    on_arm do
      sha256 "83c0a744490c35477f300e16b7b6f9409e6d67f132b0311a6465c692e58be97e"
      url "https://github.com/0xhckr/gojo/releases/download/v#{version}/gojo_#{version}_linux_arm64.tar.gz",
        verified: "github.com/0xhckr/gojo/"
    end
  end

  name "gojo"
  desc "Fullscreen terminal UI for jj (Jujutsu VCS)"
  homepage "https://github.com/0xhckr/gojo"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "jj",
    ]

  binary "gojo"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gojo"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Run `ln -sf $(which gojo) $(brew --prefix)/bin/gj` for the shorter 'gj' alias.
  EOS
end
