# This file was generated by GoReleaser. DO NOT EDIT.
cask "gojo" do
  version "1.5.0"

  on_macos do
    on_intel do
      sha256 "38ee9292afa2b5975d11089a3e5623752d616142bb22d9b7d13210e34a8fbb0d"
      url "https://github.com/0xhckr/gojo/releases/download/v#{version}/gojo_#{version}_macOS_amd64.tar.gz",
        verified: "github.com/0xhckr/gojo/"
    end
    on_arm do
      sha256 "42be0ab8744f4d65ddf017f0278be9eb78eeb5adbea7997909b3e192bd52f577"
      url "https://github.com/0xhckr/gojo/releases/download/v#{version}/gojo_#{version}_macOS_arm64.tar.gz",
        verified: "github.com/0xhckr/gojo/"
    end
  end

  on_linux do
    on_intel do
      sha256 "b4bfb9afce110d4af7ccd1a9573d13e44f46fe9f6c940a9960999bfcc8e2f728"
      url "https://github.com/0xhckr/gojo/releases/download/v#{version}/gojo_#{version}_linux_amd64.tar.gz",
        verified: "github.com/0xhckr/gojo/"
    end
    on_arm do
      sha256 "74aa67826a2d0fd6fa8197519d375b2069dd6d9d84be7949bfa6f81c416b26ee"
      url "https://github.com/0xhckr/gojo/releases/download/v#{version}/gojo_#{version}_linux_arm64.tar.gz",
        verified: "github.com/0xhckr/gojo/"
    end
  end

  name "gojo"
  desc "Fullscreen terminal UI for jj (Jujutsu VCS)"
  homepage "https://github.com/0xhckr/gojo"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "jj",
    ]

  binary "gojo"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gojo"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Run `ln -sf $(which gojo) $(brew --prefix)/bin/gj` for the shorter 'gj' alias.
  EOS
end
