# This file was generated by GoReleaser. DO NOT EDIT.
cask "gojo" do
  version "1.3.0"

  on_macos do
    on_intel do
      sha256 "4e6e659aedd17e4e4845a334f7cef867e3b1a5bbd57f7c1dbdee81412c042f39"
      url "https://github.com/0xhckr/gojo/releases/download/v#{version}/gojo_#{version}_macOS_amd64.tar.gz",
        verified: "github.com/0xhckr/gojo/"
    end
    on_arm do
      sha256 "5320c5a8da6005c66e987bb44b6caa7a683fa2353fd34b24e672cafafe07a8ab"
      url "https://github.com/0xhckr/gojo/releases/download/v#{version}/gojo_#{version}_macOS_arm64.tar.gz",
        verified: "github.com/0xhckr/gojo/"
    end
  end

  on_linux do
    on_intel do
      sha256 "aa0b411b718ebd367ef4aba3a7fb9bbfaeb73ccd5b73e6dbce8c88c2d42731fa"
      url "https://github.com/0xhckr/gojo/releases/download/v#{version}/gojo_#{version}_linux_amd64.tar.gz",
        verified: "github.com/0xhckr/gojo/"
    end
    on_arm do
      sha256 "4753165ef97b2bd1c2a9351579670367f96c839f9f99e6c48c21a7399bc0b4b5"
      url "https://github.com/0xhckr/gojo/releases/download/v#{version}/gojo_#{version}_linux_arm64.tar.gz",
        verified: "github.com/0xhckr/gojo/"
    end
  end

  name "gojo"
  desc "Fullscreen terminal UI for jj (Jujutsu VCS)"
  homepage "https://github.com/0xhckr/gojo"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "jj",
    ]

  binary "gojo"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gojo"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Run `ln -sf $(which gojo) $(brew --prefix)/bin/gj` for the shorter 'gj' alias.
  EOS
end
