# Solarized — https://ethanschoonover.com/solarized
name = "Solarized"
syntax       = "solarized-dark"
syntax_light = "solarized-light"

[dark]
background = "#002b36"
panel      = "#073642"
element    = "#0a4452"
text       = "#839496"
text_muted = "#586e75"
purple     = "#6c71c4"
blue       = "#268bd2"
green      = "#859900"
red        = "#dc322f"
yellow     = "#b58900"
cyan       = "#2aa198"
orange     = "#cb4b16"
pink       = "#d33682"
teal       = "#2aa198"

[light]
background = "#fdf6e3"
panel      = "#eee8d5"
element    = "#e0dcc6"
text       = "#657b83"
text_muted = "#93a1a1"
purple     = "#6c71c4"
blue       = "#268bd2"
green      = "#859900"
red        = "#dc322f"
yellow     = "#b58900"
cyan       = "#2aa198"
orange     = "#cb4b16"
pink       = "#d33682"
teal       = "#2aa198"
