# Tokyo Night — https://github.com/folke/tokyonight.nvim (Night + Day)
name = "Tokyo Night"

[dark]
background = "#1a1b26"
panel      = "#16161e"
element    = "#292e42"
hover      = "#1f2335"
text       = "#c0caf5"
text_muted = "#565f89"
purple     = "#9d7cd8"
magenta    = "#bb9af7"
blue       = "#7aa2f7"
green      = "#9ece6a"
red        = "#f7768e"
yellow     = "#e0af68"
cyan       = "#7dcfff"
orange     = "#ff9e64"

[light]
background = "#e1e2e7"
panel      = "#d0d5e3"
element    = "#b6bfe2"
hover      = "#c4c8da"
text       = "#3760bf"
text_muted = "#848cb5"
purple     = "#7847bd"
magenta    = "#9854f1"
blue       = "#2e7de9"
green      = "#587539"
red        = "#f52a65"
yellow     = "#8c6c3e"
cyan       = "#007197"
orange     = "#b15c00"
